### ISSUE TITLE
Allow one to translate its data

### ISSUE THREAD

**Issue by dumasl** [CS-SI/SIRIUS#10]
The issue
========

As a resampling library so far sirius does not allow to one resample on a translated grid without altering the spacing / resolution.

One possible way to solve it
======================

Translating in Fourier Domain can be done using a phase ramp.
In 1D and using the **Theoretical Basis Documentation** python code, it would look like this : 

```python

from source.code_py.simple_signal_proc import *
# create 1D signal and compute its FT
x, sincx = create_1D_sinc(50,2)
fft_sinc = np.fft.fft(np.fft.ifftshift(sincx))
# compute phase ramp
tr=np.exp(-2*1j*np.pi*-0.5*np.fft.fftfreq(fft_sinc.size))
# apply it
fft_sinc_tr = fft_sinc * tr
# get translated by -0.5 pixel signal
sincx_tr = np.fft.fftshift(np.fft.ifft(fft_sinc_tr))
plt.plot(sincx);plt.plot(sincx_tr);plt.show()
```

In this simple form this will require no filter at all (an implicit sinc interpolator is used).

**Comment by tfeuvrier-cs** [comment]
Translation functionality done by using mbelloc PR #49 which added unit test ; checked method of translation.
