### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by savmickael** [CS-SI/SIRIUS#32]
Support windows compilation (through Visual Studio Community)
Add CI through [appveyor](https://www.appveyor.com/) to check the build and the install

**Comment by savmickael** [comment]
keep in touch with @rkanavath which have a good experience on this stuff.

**Comment by tfeuvrier-cs** [comment]
AppVeyor procedures are available. Windows is supported and pushed in develop (#47).
However, building gdal is slow. Issue closed by opening the Bug #50
