### ISSUE TITLE
Support MacOSX

### ISSUE THREAD

**Issue by savmickael** [CS-SI/SIRIUS#33]
Support the last version of MacOSX
Add a CI via [TravisCI](https://travis-ci.org/) to check the build and the install

**Comment by savmickael** [comment]
Support the last version of MacOSX
Add a CI via TravisCI to check the build and the install

**Comment by dumasl** [comment]
It think all it takes is a new dockerfile and a travis matrix.
In fact, the dockerfile shall be kind of copy/pasted from the ones we have only with brew cmd instead of yum ones.

**Comment by savmickael** [comment]
keep in touch with @rkanavath which have a good experience on this stuff.

**Comment by rkanavath** [comment]
I will get a new mac next week!. so I will postpone this one to last..

**Comment by tfeuvrier-cs** [comment]
Travis file updated with Mac OSX support. Validated and pushed in develop (https://github.com/CS-SI/SIRIUS/pull/47)
