### ISSUE TITLE
Translation algorithms - testing error

### ISSUE THREAD

**Issue by tfeuvrier-cs** [CS-SI/SIRIUS#51]
The following image file lena-255x255.tif, disparity.png, triangle_10x10.tif, door.tif and half-door.tif are used in tests but not present in repository. Testing failed.

**Comment by dumasl** [comment]
That's a problem... 
I believe we can find a Lena picture somewhere. We can easily create a triangle a door and a half door too, they do not have to be large images, I guess 10x10 or 20x20 would be sufficient. 
The disparity.png image I have no clue on what it could have been...

**Comment by tfeuvrier-cs** [comment]
Yes, it's easy to generate the missing images, except "disparity.png", I decided to disable tests using this image. I understood you don't have any backup of data of mbelloc !!

**Comment by dumasl** [comment]
Yes I'm afraid we don't. I guess we decided not to push them at some point and never went back anticipating this situation. 
If you have trouble creating those let me know. We are not really loosing anything with the disparity.png image. It was a rather big data for no real reasons. The only interesting thing is it contains lots of discontinuities but the door.tif and half-door.tif are enough to envision how sirius performs with discontinuities.
